# Generated by Django 5.0.4 on 2024-04-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosmedico',
            name='cedula_identidade_medica',
            field=models.ImageField(upload_to='medico\\cim'),
        ),
        migrations.AlterField(
            model_name='dadosmedico',
            name='foto',
            field=models.ImageField(upload_to='medico\\fotos_perfil'),
        ),
        migrations.AlterField(
            model_name='dadosmedico',
            name='rg',
            field=models.ImageField(upload_to='medico\\rgs'),
        ),
    ]
