# Generated by Django 5.0.4 on 2024-04-20 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0002_alter_dadosmedico_cedula_identidade_medica_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosmedico',
            name='crm',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='dadosmedico',
            name='rg',
            field=models.ImageField(unique=True, upload_to='medico\\rgs'),
        ),
        migrations.CreateModel(
            name='HorariosDisponiveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('agendado', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
